version: '3.5'
services:
  ssh-prx:
    image: mrleerkotte/ssh-proxy-server
    ports:
      - '2222:22'
    # Specify any amount of ssh keys you would like to add to the proxy.
    # The image will loop through all SSH_KEY* environment variables and
    # add them to: /home/prx/.ssh/authorized_keys
    environment:
      - 'SSH_KEY1=<your ssh public key>'
      - 'SSH_KEY2=<your ssh public key>'
      - 'SSH_KEY...'
    volumes:
      - ssh-data:/etc/ssh

  # Add NGINX as an easy way to test the connectivity.
  nginx:
    image: nginx

volumes:
  ssh-data:
